server:
  port: 80

spring:
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboottest?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
  messages:
    basename: i18n.login

logging:
  level:
    com.springboot: debug #默认级别为info,改为info后debug日志不会打印
  path: "E:/Demo/test.log" #日志生成路径

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springboot.pojo
  configuration:
    map-underscore-to-camel-case: true #识别驼峰命名
